PRAGMA foreign_keys = OFF;

DROP TABLE IF EXISTS Purchase;
DROP TABLE IF EXISTS Rental;
DROP TABLE IF EXISTS Book;
DROP TABLE IF EXISTS User;

PRAGMA foreign_keys = ON;

CREATE TABLE User (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'USER',
  passwordHash TEXT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Book (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  author TEXT NOT NULL,
  category TEXT NOT NULL,
  year INTEGER NOT NULL,
  price INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'AVAILABLE',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL
);

CREATE TABLE Rental (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  userId INTEGER NOT NULL,
  bookId INTEGER NOT NULL,
  startsAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  endsAt DATETIME NOT NULL,
  reminded BOOLEAN NOT NULL DEFAULT false,
  CONSTRAINT Rental_userId_fkey FOREIGN KEY (userId) REFERENCES User (id),
  CONSTRAINT Rental_bookId_fkey FOREIGN KEY (bookId) REFERENCES Book (id)
);

CREATE TABLE Purchase (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  userId INTEGER NOT NULL,
  bookId INTEGER NOT NULL,
  price INTEGER NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT Purchase_userId_fkey FOREIGN KEY (userId) REFERENCES User (id),
  CONSTRAINT Purchase_bookId_fkey FOREIGN KEY (bookId) REFERENCES Book (id)
);
