PRAGMA foreign_keys = OFF;

DROP TABLE IF EXISTS Place;
DROP TABLE IF EXISTS Trip;
DROP TABLE IF EXISTS User;

PRAGMA foreign_keys = ON;

CREATE TABLE User (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  passwordHash TEXT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Trip (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  location TEXT NOT NULL,
  imageUrl TEXT,
  imageLabel TEXT NOT NULL,
  cost INTEGER NOT NULL,
  safetyScore INTEGER NOT NULL,
  authorId INTEGER NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL,
  CONSTRAINT Trip_authorId_fkey FOREIGN KEY (authorId) REFERENCES User (id)
);

CREATE TABLE Place (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  tripId INTEGER NOT NULL,
  CONSTRAINT Place_tripId_fkey FOREIGN KEY (tripId) REFERENCES Trip (id) ON DELETE CASCADE
);
