PRAGMA foreign_keys = OFF;

DROP TABLE IF EXISTS AccessRequest;
DROP TABLE IF EXISTS Subscription;
DROP TABLE IF EXISTS Comment;
DROP TABLE IF EXISTS PostTag;
DROP TABLE IF EXISTS Tag;
DROP TABLE IF EXISTS Post;
DROP TABLE IF EXISTS User;

PRAGMA foreign_keys = ON;

CREATE TABLE User (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  passwordHash TEXT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Post (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  visibility TEXT NOT NULL DEFAULT 'PUBLIC',
  authorId INTEGER NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL,
  CONSTRAINT Post_authorId_fkey FOREIGN KEY (authorId) REFERENCES User (id)
);

CREATE TABLE Tag (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE
);

CREATE TABLE PostTag (
  postId INTEGER NOT NULL,
  tagId INTEGER NOT NULL,
  PRIMARY KEY (postId, tagId),
  CONSTRAINT PostTag_postId_fkey FOREIGN KEY (postId) REFERENCES Post (id) ON DELETE CASCADE,
  CONSTRAINT PostTag_tagId_fkey FOREIGN KEY (tagId) REFERENCES Tag (id) ON DELETE CASCADE
);

CREATE TABLE Comment (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  text TEXT NOT NULL,
  postId INTEGER NOT NULL,
  authorId INTEGER NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT Comment_postId_fkey FOREIGN KEY (postId) REFERENCES Post (id) ON DELETE CASCADE,
  CONSTRAINT Comment_authorId_fkey FOREIGN KEY (authorId) REFERENCES User (id)
);

CREATE TABLE Subscription (
  followerId INTEGER NOT NULL,
  followingId INTEGER NOT NULL,
  PRIMARY KEY (followerId, followingId),
  CONSTRAINT Subscription_followerId_fkey FOREIGN KEY (followerId) REFERENCES User (id) ON DELETE CASCADE,
  CONSTRAINT Subscription_followingId_fkey FOREIGN KEY (followingId) REFERENCES User (id) ON DELETE CASCADE
);

CREATE TABLE AccessRequest (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  postId INTEGER NOT NULL,
  requesterId INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'PENDING',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL,
  CONSTRAINT AccessRequest_postId_fkey FOREIGN KEY (postId) REFERENCES Post (id) ON DELETE CASCADE,
  CONSTRAINT AccessRequest_requesterId_fkey FOREIGN KEY (requesterId) REFERENCES User (id) ON DELETE CASCADE,
  CONSTRAINT AccessRequest_postId_requesterId_key UNIQUE (postId, requesterId)
);
